#
# Makefile.cvs for xanalyser
#

configure: all
	./configure

all:
	aclocal
	autoconf
	autoheader
	automake --add-missing

install: configure
	make
	make install

reconf: all
	./config.status --recheck
	./config.status
